language: ruby
rvm:
- 2.2.2

install: gem install minima github-pages
script: bundle exec jekyll build && htmlproofer ./_site --only-4xx

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# sudo: false # route your build to the container-based infrastructure for a faster build
