# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Documentation
email: zyxneo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is a demonstrational page. It collects development tools, techniques and references
github_username: zyxneo

# Server
baseurl: "" # does not include hostname. the subpath of your site, e.g. /blog
url: "https://zyxneo.github.io" # the base hostname & protocol for your site
detach:  false
port:    4000
host:    127.0.0.1
show_dir_listing: false

# Where things are
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Handling Reading
safe:         false
include:      [".htaccess"] #[DIR, FILE, ...] Force inclusion of directories and/or files in the conversion. .htaccess is a good example since dotfiles are excluded by default.
exclude:      [vendor]
keep_files:   [".git"] #[DIR, FILE, ...] When clobbering the site destination, keep the selected files. Useful for files that are not generated by jekyll; e.g. files or assets that are generated by your build tool. The paths are relative to the destination.
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

theme: minima

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Szilágyi Balázs"
      excerpt_separator: <!--more--> # Completely disable excerpts by setting your excerpt_separator to "".

categories: [example,links,docu]
